# 連続した空行（2行以上）を禁止するルール
MD012: false

# 1行の文字数制限（デフォルト80文字）
MD013: false

# 見出しの上下に空行を強制するルール
MD022: false

# 文書内に同じ見出しが複数あるのを禁止するルール
MD024: false

# 文書内に一番大きな見出し(H1)を1つだけにするルール
MD025: false

# URLをそのまま貼り付けるのを禁止するルール（生のURL）
MD034: false

# ファイルの最初の行は最上位の見出しあるべきです
MD041: false
